version: "3.9"
services:
  db:
    image: postgres:16
    container_name: shop_postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: ChangeMe_12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d app"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
